export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

//course
export const SEARCH_COURSES = "SEARCH_COURSES";
export const INSERT_COURSE = "INSERT_COURSE";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";
export const GET_MY_COURSES = "GET_MY_COURSES";
export const GET_ALL_COURSES = "GET_ALL_COURSES";
export const GET_COURSE_BY_ID = "GET_COURSE_BY_ID";
export const GET_COURSE_BY_NAME = "GET_COURSE_BY_NAME";
export const GET_ALL_STUDENTS_OF_COURSES = "GET_ALL_STUDENTS_OF_COURSES";


export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const GET_MY_STUDENT = "GET_MY_STUDENTS";
export const GET_ALL_STUDENTS = "GET_ALL_STUDENTS";
export const GET_STUDENT_BY_ID = "GET_STUDENT_BY_ID";
export const GET_STUDENT_BY_NAME = "GET_STUDENT_BY_NAME";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const SAVE_CART = "SAVE_CART";

